<?php

namespace AppBundle\Repository;

/**
 * ADSyncRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ADSyncRepository extends \Doctrine\ORM\EntityRepository
{
}
