<?php

namespace AppBundle\Repository;

/**
 * DepartmentsTeams
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartmentsTeams extends \Doctrine\ORM\EntityRepository
{
}
