<?php

namespace AppBundle\Repository;

/**
 * DepartmentsProjects
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartmentsProjects extends \Doctrine\ORM\EntityRepository
{
}
