<?php

namespace AppBundle\Repository;

/**
 * PersonEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonEntryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $id Identifier of person
     * @return bool Return true if person is active, false if not
     */
    public function isActive($id){
        $q = $this->createQueryBuilder('pe')
            ->select(
                'CASE 
                    WHEN pe.exit_date IS NULL THEN true 
                    WHEN pe.exit_date > CURRENT_TIMESTAMP() THEN true 
                    ELSE false 
                 END as active'
            )
            ->where('pe.Person = :person_id')
            ->orderBy('pe.entry_date','DESC')
            ->setMaxResults(1)
            ->setParameter('person_id', $id)
            ->getQuery()
            ->getResult();
        if ( count($q) === 0 ) {
            return true;
        }

        return $q[0]['active'];
    }
}
