<?php

namespace AppBundle\Repository;

/**
 * PersonEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonEntryRepository extends \Doctrine\ORM\EntityRepository
{
}
