<?php

namespace AppBundle\Repository;

/**
 * PersonEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonEntryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $id Identifier of person
     * @return bool $result Return true if person is active, false if not
     */
    public function isActive($id){
        $result = true;
        $q = $this->createQueryBuilder('pe')
            ->where('pe.Person = :person_id')
            ->andWhere('CASE 
                            WHEN (pe.exit_date IS NULL) THEN
                                true
                            WHEN pe.exit_date > CURRENT_TIMESTAMP() THEN
                                true 
                            ELSE 
                                false 
                       END = true'
            )
            ->setParameter('person_id', $id)
            ->getQuery()
            ->getResult();
        if( count($q) === 0 ) {
            $result = false;
        }
        return $result;
    }
}
