<?php

namespace AppBundle\Repository;

/**
 * ProjectsMembers
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectsMembers extends \Doctrine\ORM\EntityRepository
{
}
