<?php

namespace AppBundle\Repository;

/**
 * TeamsProjects
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamsProjects extends \Doctrine\ORM\EntityRepository
{
}
