<?php

namespace AppBundle\Repository;

use AppBundle\Utils\Util as Util;

/**
 * TeamsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $name The person name searched
     * @param bool $exact Tells if search for an exact match or not
     * @param string $locale The current locale used for language corresponding specific display and search
     * @return array
     */
    public function searchInName($name, $exact = false, $locale = 'en', $exclusionTable = 'none', $exclusionId = 0) {

        $em = $this->getEntityManager();
        $conn = $em->getConnection();

        $qb = $conn->createQueryBuilder();

        $distinct = '';

        if( $exclusionTable === 'person' || $exclusionTable === 'projects' ) {
            $distinct = 'DISTINCT ';
        }

        $params = array('locale' => $locale);

        $qb
            ->select(
                "   $distinct
                    t.id as \"value\",
                    CASE
                      WHEN t.international_cascade = 2 THEN
                        t.international_name
                      WHEN t.international_cascade = 1 AND t.international_name_language = :locale THEN
                        t.international_name
                      ELSE
                        CASE
                          WHEN :locale = 'nl' THEN
                            CASE
                              WHEN t.name_nl IS NULL THEN
                                t.international_name
                              ELSE
                                t.name_nl
                            END
                          WHEN :locale = 'fr' THEN
                            CASE
                              WHEN t.name_fr IS NULL THEN
                                t.international_name
                              ELSE
                                t.name_fr
                            END
                          ELSE
                            CASE
                              WHEN t.name_en IS NULL THEN
                                t.international_name
                              ELSE
                                t.name_en
                            END
                        END
                    END as \"label\",
                 CASE
                   WHEN COALESCE(t.end_date,'2999/01/01'::timestamp) > now() THEN
                     'active'
                   ELSE
                     'inactive'
                 END as \"active\"
                "
            )
            ->from(
                'teams',
                't'
            );

        if ( $exclusionTable === 'projects' ) {
            $qb->where(
                'NOT EXISTS (
                    SELECT 1 
                    FROM teams_projects 
                    WHERE team_ref = t.id 
                      AND project_ref = :project_id 
                      AND start_date IS NULL 
                      AND end_date IS NULL
                 )'
            );
            $params['project_id'] = $exclusionId;
        }
        elseif ( $exclusionTable === 'person' ) {
            $qb->where(
                'NOT EXISTS (
                    SELECT 1 
                    FROM teams_members 
                    WHERE team_ref = t.id 
                      AND person_ref = :person_id 
                      AND start_date IS NULL 
                      AND end_date IS NULL
                 )'
            );
            $params['person_id'] = $exclusionId;
        }

        if ( $exact === true ) {
            $qb->andwhere('
                   CASE 
                       WHEN t.international_cascade = 2 THEN
                         t.international_name
                       WHEN t.international_cascade = 1 AND t.international_name_language = :locale THEN
                         t.international_name
                       ELSE
                         CASE
                           WHEN :locale = \'nl\' THEN
                             CASE
                               WHEN t.name_nl IS NULL THEN
                                 t.international_name
                               ELSE
                                 t.name_nl
                             END
                           WHEN :locale = \'fr\' THEN
                             CASE
                               WHEN t.name_fr IS NULL THEN
                                 t.international_name
                               ELSE
                                 t.name_fr
                             END
                           ELSE
                             CASE
                               WHEN t.name_en IS NULL THEN
                                 t.international_name
                               ELSE
                                 t.name_en
                             END
                         END
                   END ilike :name'
            );

            $params['name'] = $name;
        }
        else {
            foreach (explode(' ', $name) as $key => $term) {

                $term = trim($term);
                if ($term == '') continue;
                $term = Util::unaccent($term);
                $qb->andWhere("
                    translate(
                       CASE 
                           WHEN t.international_cascade = 2 THEN
                             t.international_name
                           WHEN t.international_cascade = 1 AND t.international_name_language = :locale THEN
                             t.international_name
                           ELSE
                             CASE
                               WHEN :locale = 'nl' THEN
                                 CASE
                                   WHEN t.name_nl IS NULL THEN
                                     t.international_name
                                   ELSE
                                     t.name_nl
                                 END
                               WHEN :locale = 'fr' THEN
                                 CASE
                                   WHEN t.name_fr IS NULL THEN
                                     t.international_name
                                   ELSE
                                     t.name_fr
                                 END
                               ELSE
                                 CASE
                                   WHEN t.name_en IS NULL THEN
                                     t.international_name
                                   ELSE
                                     t.name_en
                                 END
                             END
                       END, 'äàáëéèêöôîï','aaaeeeeooii'
                    ) ilike :term$key"
                );
                $params["term$key"] = '%'.$term.'%';
            }
        }

        $qb->setParameters($params)
            ->setMaxResults(300)
            ->orderBy('label,value');

        $query_prepared = $conn->prepare($qb->getSQL());
        $query_prepared->execute($qb->getParameters());

        return $query_prepared->fetchAll();

    }

    /**
     * @param string $locale The locale used to organize the groups of teams retrieved
     * @param string $letter The first letter used to get a list filtered by the team name first letter
     * @return array
     */
    public function groupsByLetters($locale = 'en', $letter = '*', $startFrom = 0) {
        $response = Util::alphaRange();
        $dbResponse = array();

        $em = $this->getEntityManager();
        $conn = $em->getConnection();
        $qb = $conn->createQueryBuilder();
        $params = array('locale' => $locale);

        $qb->select(
            " t.*,
              regexp_replace(
                  upper(
                    left(
                        CASE
                          WHEN t.international_cascade = 2 THEN
                            t.international_name
                          WHEN t.international_cascade = 1 AND t.international_name_language = :locale THEN
                            t.international_name
                          ELSE
                            CASE
                              WHEN :locale = 'nl' THEN
                                CASE
                                  WHEN t.name_nl IS NULL THEN
                                    t.international_name
                                  ELSE
                                    t.name_nl
                                 END
                              WHEN :locale = 'fr' THEN
                                CASE
                                  WHEN t.name_fr IS NULL THEN
                                    t.international_name
                                  ELSE
                                    t.name_fr
                                END
                              ELSE
                                CASE
                                  WHEN t.name_en IS NULL THEN
                                    t.international_name
                                  ELSE
                                    t.name_en
                                END
                            END
                        END,
                        1
                    )
                  ),
                  E'\\\d',
                  '#' 
              ) as firstLetter,
              CASE
                WHEN t.international_cascade = 2 THEN
                  t.international_name
                WHEN t.international_cascade = 1 AND t.international_name_language = :locale THEN
                  t.international_name
                ELSE
                  CASE
                    WHEN :locale = 'nl' THEN
                      CASE
                        WHEN t.name_nl IS NULL THEN
                          t.international_name
                        ELSE
                          t.name_nl
                       END
                    WHEN :locale = 'fr' THEN
                      CASE
                        WHEN t.name_fr IS NULL THEN
                          t.international_name
                        ELSE
                          t.name_fr
                      END
                    ELSE
                      CASE
                        WHEN t.name_en IS NULL THEN
                          t.international_name
                        ELSE
                          t.name_en
                      END
                  END
              END as \"name\",
              CASE
                WHEN COALESCE(t.end_date,'2999/01/01'::timestamp) > now() THEN
                  'active'
                ELSE
                  'inactive'
              END as \"active\",
              COUNT(id) OVER (PARTITION BY regexp_replace(
                  upper(
                    left(
                        CASE
                          WHEN t.international_cascade = 2 THEN
                            t.international_name
                          WHEN t.international_cascade = 1 AND t.international_name_language = :locale THEN
                            t.international_name
                          ELSE
                            CASE
                              WHEN :locale = 'nl' THEN
                                CASE
                                  WHEN t.name_nl IS NULL THEN
                                    t.international_name
                                  ELSE
                                    t.name_nl
                                 END
                              WHEN :locale = 'fr' THEN
                                CASE
                                  WHEN t.name_fr IS NULL THEN
                                    t.international_name
                                  ELSE
                                    t.name_fr
                                END
                              ELSE
                                CASE
                                  WHEN t.name_en IS NULL THEN
                                    t.international_name
                                  ELSE
                                    t.name_en
                                END
                            END
                        END,
                        1
                    )
                  ),
                  E'\\\d',
                  '#' 
              ) ) as counting,
              COUNT(id) OVER () as totalCounting
            "
        )
            ->from(
                'teams',
                't'
            );

        $qb->setParameters($params)
            ->setMaxResults(500)
            ->orderBy('firstLetter,name');

        if ( $startFrom !== 0 ) {
            $qb->setFirstResult($startFrom);
        }

        $query_prepared = $conn->prepare($qb->getSQL());
        $query_prepared->execute($qb->getParameters());
        $dbResponse = $query_prepared->fetchAll();

        foreach( $dbResponse as $content ) {
            $response['*']['count'] = $content['totalcounting'];
            $response[$content['firstletter']]['count']= $content['counting'];
            $response['*']['list'][] = $content;
            $response[$content['firstletter']]['list'][]= $content;
        }

        $response[$letter]['selected'] = 1;

        return $response;
    }
}
