<?php

namespace AppBundle\Repository;

/**
 * TeamsMembers
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamsMembers extends \Doctrine\ORM\EntityRepository
{
}
