<?php

namespace AppBundle\Repository;

/**
 * WorkingDuty
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkingDuty extends \Doctrine\ORM\EntityRepository
{
}
