app_rest_people:
    path: /rest/people
    defaults:
        _controller: AppBundle:Rest/People:list
        _format: "%default_rest_format%"
    requirements:
        _format: "%rest_formats%"
    methods: [GET]

app_rest_people_by_id:
    path: /rest/people/{id}
    defaults:
        _controller: AppBundle:Rest/People:listById
        _format: "%default_rest_format%"
    requirements:
        _format: "%rest_formats%"
        id: \d+
    methods: [GET]

app_rest_people_by_name:
    path: /rest/people/{name}
    defaults:
        _controller: AppBundle:Rest/People:listByName
        _format: "%default_rest_format%"
    requirements:
        _format: "%rest_formats%"
    methods: [GET]

app_rest_organigram:
    path: /rest/organigram
    defaults:
        _controller: AppBundle:Rest/Departments:listAll
        _format: "%default_rest_format%"
    requirements:
        _format: "%rest_formats%"
    methods: [GET]

app_rest_directorates:
    path: /rest/directorates
    defaults:
        _controller: AppBundle:Rest/Departments:listDirectorates
        _format: "%default_rest_format%"
    requirements:
        _format: "%rest_formats%"
    methods: [GET]

app_rest_directorates_by_id:
    path: /rest/directorates/{id}
    defaults:
        _controller: AppBundle:Rest/Departments:listById
        _format: "%default_rest_format%"
    requirements:
        _format: "%rest_formats%"
        id: \d+
    methods: [GET]

app_rest_directorates_by_name:
    path: /rest/directorates/{name}
    defaults:
        _controller: AppBundle:Rest/Departments:listByName
        _format: "%default_rest_format%"
    requirements:
        _format: "%rest_formats%"
    methods: [GET]

app_rest_services:
    path: /rest/services
    defaults:
        _controller: AppBundle:Rest/Departments:listServices
        _format: "%default_rest_format%"
    requirements:
        _format: "%rest_formats%"
    methods: [GET]

app_rest_services_by_id:
    path: /rest/services/{id}
    defaults:
        _controller: AppBundle:Rest/Departments:listById
        _format: "%default_rest_format%"
    requirements:
        _format: "%rest_formats%"
        id: \d+
    methods: [GET]

app_rest_services_by_name:
    path: /rest/services/{name}
    defaults:
        _controller: AppBundle:Rest/Departments:listByName
        _format: "%default_rest_format%"
    requirements:
        _format: "%rest_formats%"
    methods: [GET]

app_rest_projects:
    path: /rest/projects
    defaults:
        _controller: AppBundle:Rest/Projects:list
        _format: "%default_rest_format%"
    requirements:
        _format: "%rest_formats%"
    methods: [GET]

app_rest_projects_by_id:
    path: /rest/projects/{id}
    defaults:
        _controller: AppBundle:Rest/Projects:listById
        _format: "%default_rest_format%"
    requirements:
        _format: "%rest_formats%"
        id: \d+
    methods: [GET]

app_rest_projects_by_name:
    path: /rest/projects/{name}
    defaults:
        _controller: AppBundle:Rest/Projects:listByName
        _format: "%default_rest_format%"
    requirements:
        _format: "%rest_formats%"
    methods: [GET]

app_rest_teams:
    path: /rest/teams
    defaults:
        _controller: AppBundle:Rest/Teams:list
        _format: "%default_rest_format%"
    requirements:
        _format: "%rest_formats%"
    methods: [GET]

app_rest_teams_by_id:
    path: /rest/teams/{id}
    defaults:
        _controller: AppBundle:Rest/Teams:listById
        _format: "%default_rest_format%"
    requirements:
        _format: "%rest_formats%"
        id: \d+
    methods: [GET]

app_rest_teams_by_name:
    path: /rest/teams/{name}
    defaults:
        _controller: AppBundle:Rest/Teams:listByName
        _format: "%default_rest_format%"
    requirements:
        _format: "%rest_formats%"
    methods: [GET]

app_login:
    path: /{_locale}/login
    defaults:
        _controller: AppBundle:Security:login
        _locale: "%locale%"
    requirements:
        _locale: "%locales%"
    methods: [GET,POST]

app_logout:
    path: /{_locale}/logout
    defaults:
        _controller: AppBundle:Security:logout
        _locale: "%locale%"
    requirements:
        _locale: "%locales%"
    methods: [GET]

app_homepage:
    path: /{_locale}
    defaults:
        _controller: AppBundle:Default:index
        _locale: "%locale%"
    requirements:
        _locale: "%locales%"
    options:
        expose: true
    methods: [GET]

app_fastSearch:
    path: /{_locale}/search/{fast_search_type}/{exclusion_table}/{exclusion_id}
    defaults:
        _controller: AppBundle:FastSearch:fastSearch
        _locale: "%locale%"
        exclusion_table: "none"
        exclusion_id: 0
    requirements:
        _locale: "%locales%"
        fast_search_type: "%fast_search_types%"
        exclusion_id: \d+
    methods: [GET]
    condition: "request.isXmlHttpRequest()"

app_edit_related:
    path: /edit/{type}/{id}
    defaults:
        _controller: AppBundle:Default:edit
    requirements:
        type: "TeamsMembers|ProjectsMembers|TeamsProjects"
        id: \d+
    methods: [GET,POST]
    condition: "request.isXmlHttpRequest()"

app_remove_related:
    path: /remove/{type}/{id}
    defaults:
        _controller: AppBundle:Default:remove
    requirements:
        type: "TeamsMembers|ProjectsMembers|TeamsProjects|teams|projects"
        id: \d+
    methods: [POST]
    condition: "request.isXmlHttpRequest()"

app_add_related:
    path: /add/{type}/{id}/{related}/{related_id}
    defaults:
        _controller: AppBundle:Default:add
    requirements:
        type: "person|teams|projects"
        id: \d+
        related: "person|teams|projects"
        related_id: \d+
    options:
        expose: true
    methods: [POST]
    condition: "request.isXmlHttpRequest()"

adsync_list:
    path: /{_locale}/ad/list/{letter}/{active}
    defaults:
        _controller: AppBundle:ADSync:index
        _locale: "%locale%"
        letter: '*'
        active: 'active'
    requirements:
        _locale: "%locales%"
    options:
        expose: false
    methods: [GET]

adsync_sync:
    path: /{_locale}/ad/sync
    defaults:
        _controller: AppBundle:ADSync:refresh
        _locale: "%locale%"
    requirements:
        _locale: "%locales%"
    options:
        expose: false
    methods: [GET]
    condition: "request.isXmlHttpRequest()"

adsync_free_uids:
    path: /{_locale}/ad/freeuids
    defaults:
        _controller: AppBundle:ADSync:getNonUsedUids
        _locale: "%locale%"
    requirements:
        _locale: "%locales%"
    options:
        expose: false
    methods: [GET]
    condition: "request.isXmlHttpRequest()"

person_remove_uid:
    path: /{_locale}/person/uid/remove
    defaults:
        _controller: AppBundle:Person:removeUid
        _locale: "%locale%"
    requirements:
        _locale: "%locales%"
    options:
        expose: false
    methods: [POST]
    condition: "request.isXmlHttpRequest()"

person_update_uid:
    path: /{_locale}/person/uid/update
    defaults:
        _controller: AppBundle:Person:updateUid
        _locale: "%locale%"
    requirements:
        _locale: "%locales%"
    options:
        expose: false
    methods: [POST]
    condition: "request.isXmlHttpRequest()"

person_list:
    path: /{_locale}/person/list
    defaults:
        _controller: AppBundle:Person:personList
        _locale: "%locale%"
    requirements:
        _locale: "%locales%"
    options:
        expose: false
    methods: [GET]

person_list_details:
    path: /{_locale}/person/list/{letter}
    defaults:
        _controller: AppBundle:Person:personListDetails
        _locale: "%locale%"
    requirements:
        _locale: "%locales%"
        letter: "%alpha_list%"
    options:
        expose: true
    methods: [GET]
    condition: "request.isXmlHttpRequest()"

person_fragment_view:
    path: /{_locale}/person/fragment/{action}/{id}
    defaults:
        _controller: AppBundle:Person:renderPersonView
        _locale: "%locale%"
        action: "view"
        id: 0
    requirements:
        _locale: "%locales%"
        action: "view"
        id: \d+
    options:
        expose: true
    methods: [GET]

related_people_fragment_view:
    path: /{_locale}/related_people/fragment/{action}/{type}/{id}
    defaults:
        _controller: AppBundle:Person:renderRelatedPeopleView
        _locale: "%locale%"
        action: "view"
        id: 0
    requirements:
        _locale: "%locales%"
        action: "view"
        type: "teams|projects"
        id: \d+
    options:
        expose: true
    methods: [GET]

person:
    path: /{_locale}/person/{action}/{id}
    defaults:
        _controller: AppBundle:Person:person
        _locale: "%locale%"
        action: "view"
        id: 0
    requirements:
        _locale: "%locales%"
        action: "view"
        id: \d+
    options:
        expose: true
    methods: [GET]

teams_list:
    path: /{_locale}/teams/list
    defaults:
        _controller: AppBundle:Teams:teamsList
        _locale: "%locale%"
    requirements:
        _locale: "%locales%"
    options:
        expose: true
    methods: [GET]

teams_list_details:
    path: /{_locale}/teams/list/{letter}
    defaults:
        _controller: AppBundle:Teams:teamsListDetails
        _locale: "%locale%"
    requirements:
        _locale: "%locales%"
        letter: "%alpha_list%"
    options:
        expose: true
    methods: [GET]
    condition: "request.isXmlHttpRequest()"

teams_fragment_view:
    path: /{_locale}/teams/fragment/{action}/{id}
    defaults:
        _controller: AppBundle:Teams:renderTeamView
        _locale: "%locale%"
        action: "view"
        id: 0
    requirements:
        _locale: "%locales%"
        action: "view"
        id: \d+
    options:
        expose: true
    methods: [GET]

related_teams_fragment_view:
    path: /{_locale}/related_teams/fragment/{action}/{type}/{id}
    defaults:
        _controller: AppBundle:Teams:renderRelatedTeamsView
        _locale: "%locale%"
        action: "view"
        id: 0
    requirements:
        _locale: "%locales%"
        action: "view"
        type: "projects|person"
        id: \d+
    options:
        expose: true
    methods: [GET]

teams:
    path: /{_locale}/teams/{action}/{id}
    defaults:
        _controller: AppBundle:Teams:teams
        _locale: "%locale%"
        action: "add"
        id: 0
    requirements:
        _locale: "%locales%"
        action: "%default_possible_actions%"
        id: \d+
    options:
        expose: true
    methods: [GET,POST]

projects_list:
    path: /{_locale}/projects/list
    defaults:
        _controller: AppBundle:Projects:projectsList
        _locale: "%locale%"
    requirements:
        _locale: "%locales%"
    options:
        expose: true
    methods: [GET]

projects_list_details:
    path: /{_locale}/projects/list/{letter}
    defaults:
        _controller: AppBundle:Projects:projectsListDetails
        _locale: "%locale%"
    requirements:
        _locale: "%locales%"
        letter: "%alpha_list%"
    options:
        expose: true
    methods: [GET]
    condition: "request.isXmlHttpRequest()"

projects_fragment_view:
    path: /{_locale}/projects/fragment/{action}/{id}
    defaults:
        _controller: AppBundle:Projects:renderProjectView
        _locale: "%locale%"
        action: "view"
        id: 0
    requirements:
        _locale: "%locales%"
        action: "view"
        id: \d+
    options:
        expose: true
    methods: [GET]

related_projects_fragment_view:
    path: /{_locale}/related_projects/fragment/{action}/{type}/{id}
    defaults:
        _controller: AppBundle:Projects:renderRelatedProjectsView
        _locale: "%locale%"
        action: "view"
        id: 0
    requirements:
        _locale: "%locales%"
        action: "view"
        type: "teams|person"
        id: \d+
    options:
        expose: true
    methods: [GET]

projects:
    path: /{_locale}/projects/{action}/{id}
    defaults:
        _controller: AppBundle:Projects:projects
        _locale: "%locale%"
        action: "add"
        id: 0
    requirements:
        _locale: "%locales%"
        action: "%default_possible_actions%"
        id: \d+
    options:
        expose: true
    methods: [GET,POST]

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

remove_trailing_slash:
    path: /{url}
    defaults:
      _controller: AppBundle:Redirecting:removeTrailingSlash
    requirements:
        url: .*/$
    methods: [GET]
