app_homepage:
    path: /{_locale}
    defaults:
      _controller: AppBundle:Default:index
      _locale: "%locale%"
    requirements:
      _locale: "%locales%"
    methods: [GET]

app_fastSearch:
    path: /{_locale}/search/{fast_search_type}
    defaults:
      _controller: AppBundle:FastSearch:fastSearch
      _locale: "%locale%"
    requirements:
      _locale: "%locales%"
      fast_search_type: "%fast_search_types%"
    methods: [GET]

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
