app_homepage:
    path: /{_locale}
    defaults:
      _controller: AppBundle:Default:index
      _locale: "%locale%"
    methods: [GET]

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
