app_homepage:
    path: /{_locale}
    defaults:
        _controller: AppBundle:Default:index
        _locale: "%locale%"
    requirements:
        _locale: "%locales%"
    methods: [GET]

app_fastSearch:
    path: /{_locale}/search/{fast_search_type}
    defaults:
        _controller: AppBundle:FastSearch:fastSearch
        _locale: "%locale%"
    requirements:
        _locale: "%locales%"
        fast_search_type: "%fast_search_types%"
    methods: [GET]

person:
    path: /{_locale}/person/{action}/{id}
    defaults:
        _controller: AppBundle:Person:person
        _locale: "%locale%"
        action: "add"
        id: 0
    requirements:
        _locale: "%locales%"
        action: "%default_possible_actions%"
        id: \d+
    options:
        expose: true
    methods: [GET,POST]

teams:
    path: /{_locale}/teams/{action}/{id}
    defaults:
        _controller: AppBundle:Teams:teams
        _locale: "%locale%"
        action: "add"
        id: 0
    requirements:
        _locale: "%locales%"
        action: "%default_possible_actions%"
        id: \d+
    options:
        expose: true
    methods: [GET,POST]

projects:
    path: /{_locale}/projects/{action}/{id}
    defaults:
        _controller: AppBundle:Projects:projects
        _locale: "%locale%"
        action: "add"
        id: 0
    requirements:
        _locale: "%locales%"
        action: "%default_possible_actions%"
        id: \d+
    options:
        expose: true
    methods: [GET,POST]

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

remove_trailing_slash:
    path: /{url}
    defaults:
      _controller: AppBundle:Redirecting:removeTrailingSlash
    requirements:
        url: .*/$
    methods: [GET]
