# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\Person: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        db_users:
            entity: { class: AppBundle\Entity\Person, property: uid }
        ldap_users:
            ldap:
                service: app.security.ldap
                base_dn: "cn=Users,dc=%ldap_domain%,dc=%ldap_domain_ext%"
                search_dn: "cn=%ldap_user%,ou=%ldap_ou%,dc=%ldap_domain%,dc=%ldap_domain_ext%"
                search_password: "%ldap_pwd%"
                default_roles: [ROLE_USER]
                filter: (&(ObjectClass=Person)({uid_key}={username}))
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        rest:
            pattern: ^/rest/
            anonymous: true
            stateless: true
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - app.security.login_form_ldap_authenticator
                entry_point: app.security.login_form_ldap_authenticator
            logout:
                path: app_logout
                target: app_login
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    role_hierarchy:
        ROLE_TP_LEADER: ROLE_USER
        ROLE_HR_EDIT: ROLE_USER
        ROLE_HR_VIEWER: ROLE_USER
        ROLE_HR: ROLE_TP_LEADER
        ROLE_HR_ADMIN: ROLE_HR
        ROLE_ADMIN: ROLE_HR
        Administrators: ROLE_ADMIN
        dbadmins: ROLE_ADMIN
        hr-it: ROLE_ADMIN
        devel-ict: ROLE_ADMIN
        ROLE_HR_SUPERADMIN: ROLE_ADMIN
        HR_superadmin: ROLE_ADMIN

    access_control:
        - { path: app_login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/rest, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(|en|fr|nl)$, roles: ROLE_USER }
        - { path: ^/(en|fr|nl)/(projects|teams|person)/(list|view), roles: ROLE_USER }
        - { path: ^/(en|fr|nl)/(projects|teams|person)/(add|edit), roles: ROLE_TP_LEADER }
        - { path: ^/(en|fr|nl)/(projects|teams|person)$, roles: ROLE_TP_LEADER }
        - { path: ^/(edit|add|remove), roles: ROLE_TP_LEADER }
