# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    twig_asset_version_extension:
        class: AppBundle\Twig\AssetVersionExtension
        arguments: ["%kernel.root_dir%"]
        tags:
            - { name: twig.extension }
    correct_dates_validator:
        class: AppBundle\Validator\CorrectDatesValidator
        tags:
            - { name: validator.constraint_validator , alias: correct_dates }
    app.security.ldap:
        class: Symfony\Component\Ldap\Ldap
        arguments: [ "%ldap_server%" ]
        autowire: true
    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true
