AppBundle\Entity\DepartmentsProjects:
  type: entity
  repositoryClass: AppBundle\Repository\DepartmentsProjects
  table: departments_projects
  id:
    id:
      type: integer
      generator:
        strategy: IDENTITY
  fields:
    start_date:
      type: date
      nullable: true
      options:
        comment: 'Project start date in the given department'
        check: "CONSTRAINT departments_projects_start_date CHECK (CASE WHEN end_date IS NOT NULL THEN start_date IS NOT NULL OR start_date <= end_date END)"
    end_date:
      type: date
      nullable: true
      options:
        comment: 'Project end date in the given department'
        check: "CONSTRAINT departments_projects_end_date CHECK (CASE WHEN start_date IS NULL THEN end_date IS NULL ELSE end_date IS NULL OR end_date >= start_date END)"
    comment:
      type: string
      nullable: true
      options:
        comment: 'Comment'
  manyToOne:
    Department:
      targetEntity: AppBundle\Entity\Department
      inversedBy: DepartmentsProjects
      joinColumn:
        name: department_ref
        nullable: false
        referencedColumnName: id
    Projects:
      targetEntity: AppBundle\Entity\Projects
      inversedBy: DepartmentsProjects
      joinColumn:
        name: project_ref
        nullable: false
        referencedColumnName: id
