AppBundle\Entity\Department:
  type: entity
  repositoryClass: AppBundle\Repository\DepartmentRepository
  table: department
  id:
    id:
      type: integer
      generator:
        strategy: IDENTITY
  fields:
    level:
      type: text
      nullable: false
      options:
        comment: 'Level in the hierarchy of organization'
    path:
      type: text
      options:
        default: '/'
        comment: 'Hierarchic path of id in the organization'
    code:
      type: string
      options:
        comment: 'Code given to Section or Department'
    name_fr:
      type: text
      options:
        comment: 'Name of department/service in french'
    name_en:
      type: text
      options:
        comment: 'Name of department/service in english'
    name_nl:
      type: text
      options:
        comment: 'Name of department/service in dutch'
    is_active:
      type: boolean
      nullable: false
      options:
        default: true
        comment: 'Flag telling if the entry is active or not'
  uniqueConstraints:
    unq_department_code:
      columns: code
  oneToMany:
    WorkingDuty:
      targetEntity: AppBundle\Entity\WorkingDuty
      mappedBy: Department
      joinColumn:
        name: id
        referencedColumnName: department_ref
        nullable: false
    DepartmentsProjects:
      targetEntity: AppBundle\Entity\DepartmentsProjects
      mappedBy: Department
      joinColumn:
        name: id
        referencedColumnName: department_ref
        nullable: false
    DepartmentsTeams:
      targetEntity: AppBundle\Entity\DepartmentsTeams
      mappedBy: Department
      joinColumn:
        name: id
        referencedColumnName: department_ref
        nullable: false
    Children:
      targetEntity: Department
      mappedBy: Parent

  manyToOne:
    Parent:
      targetEntity: Department
      inversedBy: Children
      joinColumn:
        name: parent_ref
        referencedColumnName: id

