AppBundle\Entity\DepartmentsTeams:
  type: entity
  repositoryClass: AppBundle\Repository\DepartmentsTeams
  table: departments_teams
  id:
    id:
      type: integer
      generator:
        strategy: IDENTITY
  fields:
    start_date:
      type: date
      nullable: true
      options:
        comment: 'Team creation date in the given department'
    end_date:
      type: date
      nullable: true
      options:
        comment: 'Team end date in the given department'
    comment:
      type: string
      nullable: true
      options:
        comment: 'Comment'
  manyToOne:
    Department:
      targetEntity: AppBundle\Entity\Department
      inversedBy: DepartmentsTeams
      joinColumn:
        name: department_ref
        nullable: false
        referencedColumnName: id
    Teams:
      targetEntity: AppBundle\Entity\Teams
      inversedBy: DepartmentsTeams
      joinColumn:
        name: team_ref
        nullable: false
        referencedColumnName: id
