AppBundle\Entity\Person:
  type: entity
  repositoryClass: AppBundle\Repository\PersonRepository
  table: person
  id:
    id:
      type: integer
      generator:
        strategy: IDENTITY
  fields:
    first_name:
      type: text
      options:
        comment: 'First name'
    last_name:
      type: text
      options:
        comment: 'Last name'
    matricule:
      type: text
      nullable: true
      options:
        default: ''
        comment: 'Institution internal identifier (matricule)'
    uid:
      type: text
      nullable: true
      options:
        comment: 'Unique identifier associated from AD (Active Directory)'
    email:
      type: text
      nullable: true
      options:
        comment: 'Person main email'
  uniqueConstraints:
    unq_person_uid:
      columns: uid
  oneToMany:
    WorkingDuty:
      targetEntity: AppBundle\Entity\WorkingDuty
      mappedBy: Person
      joinColumn:
        name: id
        referencedColumnName: person_ref
        nullable: false
      cascade: ["persist"]
      orderBy:
        start_date: asc
    ProjectsMembers:
      targetEntity: AppBundle\Entity\ProjectsMembers
      mappedBy: Person
      joinColumn:
        name: id
        referencedColumnName: person_ref
        nullable: false
      cascade: ["persist"]
      orderBy:
        start_date: asc
    TeamsMembers:
      targetEntity: AppBundle\Entity\TeamsMembers
      mappedBy: Person
      joinColumn:
        name: id
        referencedColumnName: person_ref
        nullable: false
      cascade: ["persist"]
      orderBy:
        start_date: asc
    PersonEntry:
      targetEntity: AppBundle\Entity\PersonEntry
      mappedBy: Person
      joinColumn:
        name: id
        referencedColumnName: person_ref
        nullable: false
      cascade: ["persist"]
      orderBy:
        entry_date: asc
