AppBundle\Entity\ProjectsMembers:
  type: entity
  repositoryClass: AppBundle\Repository\ProjectsMembers
  table: projects_members
  id:
    id:
      type: integer
      generator:
        strategy: IDENTITY
  fields:
    start_date:
      type: date
      nullable: true
      options:
        comment: 'Entry date of the person on the project'
        check: "CONSTRAINT projects_members_start_date CHECK (CASE WHEN end_date IS NOT NULL THEN start_date IS NOT NULL OR start_date <= end_date END)"
    end_date:
      type: date
      nullable: true
      options:
        comment: 'Exit date of the person on the project'
        check: "CONSTRAINT projects_members_end_date CHECK (CASE WHEN start_date IS NULL THEN end_date IS NULL ELSE end_date IS NULL OR end_date >= start_date END)"
    comment:
      type: string
      nullable: true
      options:
        comment: 'Comment'
  manyToOne:
    Person:
      targetEntity: AppBundle\Entity\Person
      inversedBy: ProjectsMembers
      joinColumn:
        name: person_ref
        nullable: false
        referencedColumnName: id
    Projects:
      targetEntity: AppBundle\Entity\Projects
      inversedBy: ProjectsMembers
      joinColumn:
        name: project_ref
        nullable: false
        referencedColumnName: id
